### ISSUE TITLE
When trying to install 2152 respond that superuser privilege is needed

### ISSUE THREAD

**Issue by alillebakk** [PLCnext/Docker_GettingStarted#1]
admin@axcf2152:/opt/plcnext/Docker_GettingStarted$ ./setup.sh
gzip: invalid magic
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Installing files...
chown: changing ownership of './archive/etc/nftables/balena.nft': Operation not                                                            permitted
chown: changing ownership of './archive/etc/nftables': Operation not permitted
chown: changing ownership of './archive/etc/init.d/balenafw': Operation not perm                                                           itted
chown: changing ownership of './archive/etc/init.d/balena': Operation not permit                                                           ted
chown: changing ownership of './archive/etc/init.d': Operation not permitted
chown: changing ownership of './archive/etc/balena-engine/daemon.json': Operatio                                                           n not permitted
chown: changing ownership of './archive/etc/balena-engine': Operation not permit                                                           ted
chown: changing ownership of './archive/etc': Operation not permitted
chown: changing ownership of './archive/README.md': Operation not permitted
chown: changing ownership of './archive': Operation not permitted
cp: cannot create regular file '/etc/init.d/./balena': Permission denied
cp: cannot create regular file '/etc/init.d/./balenafw': Permission denied
cp: preserving times for '/etc/init.d/.': Operation not permitted
cp: cannot create directory '/etc/balena-engine/': Permission denied
cp: preserving times for '/etc/nftables/./balena.nft': Operation not permitted
cp: preserving times for '/etc/nftables/.': Operation not permitted
Connecting to ftp.de.debian.org (141.76.2.4:80)
wget: can't open 'cgroupfs-mount_1.1_all.deb': File exists
dpkg: error: requested operation requires superuser privilege
groupadd: PAM: Permission denied
usermod: group 'docker' does not exist
update-rc.d: /etc/init.d/cgroupfs-mount: file does not exist
update-rc.d: /etc/init.d/balena: file does not exist

   Installation successful!
 _           _
| |__   __ _| | ___ _ __   __ _
| '_ \ / _` | |/ _ \ '_ \ / _` |
| |_) | (_| | |  __/ | | | (_| |
|_.__/ \__,_|_|\___|_| |_|\__,_|

the container engine for the IoT
admin@axcf2152:/opt/plcnext/Docker_GettingStarted$

**Comment by mluhmann** [comment]
Hello,
yes, that's right. You need to be logged in as root to run the installation successfully.
You can read it in the [README](https://github.com/PLCnext/Docker_GettingStarted/blob/master/getting-started/Part-01/README.md)
