### ISSUE TITLE
Update daemon.json of docker from "balena" to "docker"

### ISSUE THREAD

**Issue by OWarneke** [PLCnext/Docker_GettingStarted#10]
Shouldnt this 
"data-root": "/media/rfs/rw/var/lib/balena", 
be
"data-root": "/media/rfs/rw/var/lib/docker",
at
https://github.com/PLCnext/Docker_GettingStarted/blob/master/archive/docker/etc/docker/daemon.json

or is this intentional to reuse the same folder for multiple version?

**Comment by mluhmann** [comment]
This is intentional. It helps to switch easily between docker and balena without losing data.
