### ISSUE TITLE
./setup.sh <ENGINE> no longer supported

### ISSUE THREAD

**Issue by OWarneke** [PLCnext/Docker_GettingStarted#11]
https://github.com/PLCnext/Docker_GettingStarted/blob/master/getting-started/Part-01/README.md

./setup.sh < ENGINE > is no longer supported
In the past I could chose the engine to install by parameter.
This is no longer possible for automatic setup processes this was quite usefull.

also i think
./setup.sh < VERSION > like it is documented is not supported as well

**Comment by mluhmann** [comment]
Will be fixed with 2021.0 LTS
