### ISSUE TITLE
Installation of docker-compose is placing the binary in the path /usr/local/bin which is not in the PATH

### ISSUE THREAD

**Issue by DominiqueRakowskiPxCFR** [PLCnext/Docker_GettingStarted#16]
Hi,

When installing Docker with the compose option, the script is creating a folder with the following path : /usr/local/bin, but this folder is not present in the PATH, therefore, the command "docker-compose" cannot be called from anywhere.

You need to add the path to this folder in the PATH to call it : 

`export PATH="$PATH:/usr/local/bin"`

**Comment by martinboers** [comment]
The repository has been updated, and that should solve this problem.

**Comment by DominiqueRakowskiPxCFR** [comment]
Hi, thank you for the correction, however I noticed that in the script there is still an "mkdir /usr/bin" even though the directory is already present.

I think this line is not necessary.

**Comment by mluhmann** [comment]
We need to make sure that the folder is available. We can perform a check via if and then set it if it's not available or we can just try to create it (as we are doing now) and ignore the error if it already exists.
