### ISSUE TITLE
Do not Update to FW 2022.0.3 when this installation procedure was used.

### ISSUE THREAD

**Issue by OWarneke** [PLCnext/Docker_GettingStarted#18]
Adding users/groups is a change that is not FW update save.
Please use the available groups and users available by default plcnext_firmware:plcnext

https://github.com/PLCnext/Docker_GettingStarted/blob/5e977980fc025cdf550a7db5b4511e3b8cd6ae0f/setup.sh#L173

The [balena apps ](https://www.plcnextstore.com/1032) are not effected by this issue.

Error during PLC Start:
```
Starting service plcnext
set plcnext exports
I/O error : permission denied:
Fatal error occurs in application 'MainProcess':
Exception occurs: Exception of type 'Arp::System::Commons::Io:NotExistException' was thrown
'/etc/plcnext/Device.acf.settings' does not exist
```

A possible workaround:
1. execute Type 1 reset (or delete /media/rfs/rw/etc/groups)
2. update the FW to 2022.X
3. install Docker again. (re create docker / balena group)

**Comment by mjan-pxcd** [comment]
Problem with PLCnext FW after changing UUID und GUID in the system. No Problem of the container project. 
-> Closed
