### ISSUE TITLE
Docker problem

### ISSUE THREAD

**Issue by Spoikka** [PLCnext/Docker_GettingStarted#19]
Having installed Docker as you instructed, the docker doesn't work. The error message is 'Can't connect connect to docker.sock. Are you sure docker daemon is running?'

Any insight on this issue will be appreciated.

Thank you.

**Comment by mluhmann** [comment]
This is not an error message from us. But it looks like there went something wrong with you installation procedure. More information would be necessary. Are there any issues output while running the installation script? Is the daemon running (use htop and search for balena or docker tasks)? Did you perform a restart? What is the command you run and leading to this issue?

**Comment by nambach172** [comment]
![image](https://user-images.githubusercontent.com/107108268/172577097-34778529-df06-4d80-ba5e-557ccddcfb3d.png)
i have met the same proble, How can i fix it ? i has SD card ( main require of this topic )

**Comment by mluhmann** [comment]
The first problem I can see, is that your controller seems not be able to download the necessary docker-compose script. Probably your system time is not set correctly and as I can see, you didn't use the command to fix this correctly.

You have to replace the part in the double apostrophes by the correct year and time like so : 
```
date -s "2022-06-08 11:14:00"
```
Then run the install script again.

The second issue seems to be, that the daemon does not start. This could also be an issue with the correct system time and a restart of the controller could also help.

But all in all, it should work without any issues. I ran the installation process after a reset type 1 and with FW 22.0.
searching in `htop` shows me the following:
![image](https://user-images.githubusercontent.com/44058107/172581687-305b953f-e237-49f7-9131-b5b8a7fdbcb3.png)

And running the hello-world example executes successfully as well:
![image](https://user-images.githubusercontent.com/44058107/172582327-5ac24d11-8c87-4deb-a4af-fa2575b6d705.png)

**Comment by nambach172** [comment]
Thank for quickly reply, but i follow your instruction, but the problem stay the same 
![image](https://user-images.githubusercontent.com/107108268/172594139-df18b469-4ceb-4f0c-bd15-0074c1f0806e.png)

**Comment by mluhmann** [comment]
you need to run the script after you have fixed the time issue

**Comment by nambach172** [comment]
![image](https://user-images.githubusercontent.com/107108268/172654513-27756e41-f9dd-4350-a0f1-fcf35bfb2f56.png)
thanks, but typing script like the post, but it still show the error : is the balenaengine daemon running ? 
Can anyone help me fix it via teamview or anydesk ? 
Thank so much

**Comment by mluhmann** [comment]
@Spoikka: The original issue should be solved with todays update.

@nambach172 
Please do a successful firmware reset (yours didn't in the screenshot did not work!) Probably you should follow the instructions on in the user manual of your controller. This can be found [here](https://www.plcnext.help/te/Hardware/Hardware_documentation.htm). Search for **"Default setting type 1"**.

After a successful reset, please use the app for Balena and Portainer to manage container on the controller.
Follow the instructions for installation of free apps, found [here (online)](https://store.plcnext.help/st/Installing_apps_and_libraries/Installing_an_app/Online_installing_a_free_app.htm) and [here (offline)](https://store.plcnext.help/st/Installing_apps_and_libraries/Installing_an_app/Offline_installing_a_free_app.htm).

Here are the according search link for the Balena app in the app store: [Balena](https://www.plcnextstore.com/eu/search?name=balena) and links for Portainer [ARM](https://www.plcnextstore.com/eu/app/1325) and [x86](https://www.plcnextstore.com/eu/app/1326)

**Comment by nambach172** [comment]
hello ! I really don't know why balena deamon is not running, maybe I
should downgrade the firmware as instructed on github, the version is now
2022.3, I will downgrade to 202.0
