### ISSUE TITLE
Missing File archive/nftables/balena.nft

### ISSUE THREAD

**Issue by OWarneke** [PLCnext/Docker_GettingStarted#2]
In the chapter
Docker_GettingStarted/getting-started/Part-02/README.md
"For the automatically loaded ruleset see archive/nftables/balena.nft"

This file is missing.

**Comment by mluhmann** [comment]
With firmware 2020.3 the balena.nft is included and only need to be activated by the installer. I will change the readme accordingly.

**Comment by OWarneke** [comment]
reopen until fixed

**Comment by mluhmann** [comment]
Due to the changes of FW 2020.6 and the integration of xtables makes this issue obsolete. The text is changed accordingly.
